### ISSUE TITLE
Cannot install it in Kodi 17.1

### ISSUE THREAD

**Issue by Tuchkata** [harrygg/plugin.video.gong.play#2]
Hi,

I've tried several ways to install the addon, but until now without success. I've tried to install it from SuperRepo Language English [Isengard][v7] and from a .ZIP file downloaded from here : http://kodi-addons.club/addon/plugin.video.gong.play/1.5.4. Any further ideas how to proceed? Thanks in advance.

**Comment by Tuchkata** [comment]
So, I was able to install it, but now can't start any stream. What I get as an error is the following : 
`15:58:34.260 T:1564566432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: //i.cdn.bg/ntv.live/ya7SK63Y2i/c78f753d5e88af88ab36be747040f2ae?league=formula1&payment=payment&value=6782
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gong.play/addon.py", line 152, in <module>
                                                Streams(url)
                                              File "/storage/.kodi/addons/plugin.video.gong.play/addon.py", line 49, in Streams
                                                streams = gong.get_game_stream(match_url)
                                              File "/storage/.kodi/addons/plugin.video.gong.play/resources/lib/gongplay.py", line 238, in get_game_stream
                                                self.request(matches[0])
                                              File "/storage/.kodi/addons/plugin.video.gong.play/resources/lib/gongplay.py", line 76, in request
                                                res = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 421, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
                                            ValueError: unknown url type: //i.cdn.bg/ntv.live/ya7SK63Y2i/c78f753d5e88af88ab36be747040f2ae?league=formula1&payment=payment&value=6782
                                            -->End of Python script error report<--
15:58:34.765 T:1946044960   ERROR: GetDirectory - Error getting plugin://plugin.video.gong.play/?mode=2&name=%5bB%5d29%20%d0%b0%d0%bf%d1%80%2015%3a00%5b%2fB%5d%20%5bCOLOR%20white%5d%5bCOLOR%20green%5d%5bB%5dLive!%5b%2fB%5d%5b%2fCOLOR%5d%20%d0%a4%d0%be%d1%80%d0%bc%d1%83%d0%bb%d0%b0%201%20-%20%d0%9a%d0%b2%d0%b0%d0%bb%d0%b8%d1%84%d0%b8%d0%ba%d0%b0%d1%86%d0%b8%d0%b8%5b%2fCOLOR%5d&url=http%3a%2f%2fplay.gong.bg%2fwatch%2fmatch%2f6782%2f%25D0%25A4%25D0%25BE%25D1%2580%25D0%25BC%25D1%2583%25D0%25BB%25D0%25B0-1-%25D0%259A%25D0%25B2%25D0%25B0%25D0%25BB%25D0%25B8%25D1%2584%25D0%25B8%25D0%25BA%25D0%25B0%25D1%2586%25D0%25B8%25D0%25B8%2f&vbstart
15:58:34.775 T:1946044960   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gong.play/?mode=2&name=%5bB%5d29%20%d0%b0%d0%bf%d1%80%2015%3a00%5b%2fB%5d%20%5bCOLOR%20white%5d%5bCOLOR%20green%5d%5bB%5dLive!%5b%2fB%5d%5b%2fCOLOR%5d%20%d0%a4%d0%be%d1%80%d0%bc%d1%83%d0%bb%d0%b0%201%20-%20%d0%9a%d0%b2%d0%b0%d0%bb%d0%b8%d1%84%d0%b8%d0%ba%d0%b0%d1%86%d0%b8%d0%b8%5b%2fCOLOR%5d&url=http%3a%2f%2fplay.gong.bg%2fwatch%2fmatch%2f6782%2f%25D0%25A4%25D0%25BE%25D1%2580%25D0%25BC%25D1%2583%25D0%25BB%25D0%25B0-1-%25D0%259A%25D0%25B2%25D0%25B0%25D0%25BB%25D0%25B8%25D1%2584%25D0%25B8%25D0%25BA%25D0%25B0%25D1%2586%25D0%25B8%25D0%25B8%2f&vbstart) failed
15:58:59.236 T:1858073504   ERROR: Unable to find plugin
15:58:59.237 T:1946044960   ERROR: GetDirectory - Error getting plugin://
15:58:59.241 T:1946044960   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
15:59:01.829 T:1946044960   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
15:59:41.904 T:1946044960  NOTICE: VideoPlayer: Opening:
15:59:41.904 T:1946044960 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:59:41.912 T:1551700896  NOTICE: Creating InputStream
15:59:42.682 T:1551700896   ERROR: Error on dvdnav_open
15:59:42.683 T:1551700896   ERROR: CVideoPlayer::OpenInputStream - error opening []
15:59:42.688 T:1551700896  NOTICE: CVideoPlayer::OnExit()
15:59:42.718 T:1946044960   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gong.play/?url=&mode=3&name=%5BB%5D2017-04-29+15%3A00%5B%2FB%5D+%5BCOLOR+white%5D%5BCOLOR+green%5D%5BB%5DLive%21%5B%2FB%5D%5B%2FCOLOR%5D+%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0+1+-+%D0%9A%D0%B2%D0%B0%D0%BB%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8%5B%2FCOLOR%5D+1&vbstart=]
15:59:42.796 T:1946044960  NOTICE: CVideoPlayer::CloseFile()
15:59:42.797 T:1946044960  NOTICE: VideoPlayer: waiting for threads to exit
15:59:42.797 T:1946044960  NOTICE: VideoPlayer: finished waiting
15:59:42.800 T:1946044960  NOTICE: CVideoPlayer::CloseFile()
15:59:42.800 T:1946044960  NOTICE: VideoPlayer: waiting for threads to exit
15:59:42.802 T:1946044960  NOTICE: VideoPlayer: finished waiting
16:02:54.235 T:1946044960  NOTICE: VideoPlayer: Opening:
16:02:54.241 T:1946044960 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:02:54.243 T:1858073504  NOTICE: Creating InputStream
16:02:54.270 T:1858073504   ERROR: Error on dvdnav_open
16:02:54.271 T:1858073504   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:02:54.271 T:1858073504  NOTICE: CVideoPlayer::OnExit()
16:02:54.273 T:1946044960   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gong.play/?url=&mode=3&name=%5BB%5D2017-04-29+15%3A00%5B%2FB%5D+%5BCOLOR+white%5D%5BCOLOR+green%5D%5BB%5DLive%21%5B%2FB%5D%5B%2FCOLOR%5D+%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0+1+-+%D0%9A%D0%B2%D0%B0%D0%BB%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8%5B%2FCOLOR%5D+2&vbstart=]
16:02:54.410 T:1946044960  NOTICE: CVideoPlayer::CloseFile()
16:02:54.411 T:1946044960  NOTICE: VideoPlayer: waiting for threads to exit
16:02:54.411 T:1946044960  NOTICE: VideoPlayer: finished waiting
16:02:54.412 T:1946044960  NOTICE: CVideoPlayer::CloseFile()
16:02:54.413 T:1946044960  NOTICE: VideoPlayer: waiting for threads to exit
16:02:54.413 T:1946044960  NOTICE: VideoPlayer: finished waiting`

This is when I am using playapi.gong.bg. With play.gong.bg I can't even start it.

**Comment by harrygg** [comment]
I'am sorry I don't have a paid subscription for gong anymore and I can't test it to see if it's working.

**Comment by Tuchkata** [comment]
Can you give me some more information how to build and install it afterwards. I will try to fix the issue in the following weeks and make a pull request if I am able to.

**Comment by harrygg** [comment]
You can install by downloading the git repo as zip archive or from BG-Addons repository (Install BG-Addons first http://blog.kodibg.org/%D0%B1%D0%B3-%D0%B0%D0%B4%D0%BE%D0%BD%D1%81-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5/)

**Comment by Tuchkata** [comment]
Maybe more information about how to build, so that once I make any changes, I can then apply them

**Comment by harrygg** [comment]
There is nothing to build. You can edit the addon .py files directly and Kodi will read the changes once you start the addon.

**Comment by Tuchkata** [comment]
So make changes, than create the zip and install it, right?

**Comment by harrygg** [comment]
It's easier to install first, then edit the files of the installed addon in the Kodi addons folder.

**Comment by Tuchkata** [comment]
Ok, great will try it. Thanks for the support.
